name: PNPM build
run-name: ${{ github.actor }} Test build 🚀
on: [push]

jobs:
  test-build:
    name: Build and Create Tagged Release
    runs-on: ubuntu-latest
    steps:
       - uses: pnpm/action-setup@v2.0.1
         with:
            version: 8.6.0

       - uses: actions/setup-node@v2
         with:
            node-version: 16.x
            cache: "pnpm"
            cache-dependency-path: "web/pnpm-lock.yaml"

       - name: Install dependencies
         run: pnpm install
         working-directory: web

       - name: Run build
         run: pnpm build
         working-directory: web
         env:
            CI: false